'use strict';

// tests for getCurrencyRates
// Generated by serverless-jest-plugin

const mod = require('./../src/get-currency-rate');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
// @ts-ignore
const wrapped = lambdaWrapper.wrap(mod, { handler: 'getCurrencyRates' });

describe('getCurrencyRates', () => {
  beforeAll((done) => {
//  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });
  
  it('implement tests here', () => {
    const stub = {};
    expect(stub).toBeDefined();
  });
});
