'use strict';

// tests for updateCurrencyQuotesScheduler
// Generated by serverless-jest-plugin

const mod = require('./../src/update-currency-quotes');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'updateCurrencyQuotes' });

describe('updateCurrencyQuotesScheduler', () => {
  beforeAll((done) => {
//  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then((response) => {
      expect(response).toBeDefined();
    });
  });
});
