name: currency-alarm-api-ci

on: [push]

jobs:
  test:
    name: app-work-properly
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      NODE_ENV: production

    strategy:
      fail-fast: true
      matrix:
        node-version: [12.x]
    steps:
      - name: Report the situation
        uses: |
        echo "NODE_ENV=$NODE_ENV".

      - name: Jump on main branch
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }} env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and build app
        run: npm i && npm run build

      - name: Run tests
        run: npm run test
      
      - run: echo "I'm fine"